<script setup lang="ts">
import EnCard from '@/Components/EnCard.vue';
import EnInput from '@/Components/EnInput.vue';
import SuperAdminSidePanel from '@/Components/SuperAdminSidePanel.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { ChevronDown, Search, Settings, Store, UserCheck, Users, UserX, WalletCards, X } from '@lucide/vue';
import { ref } from 'vue';

const props = defineProps<{
    tenants: { data: Array<{ id: string; subscriber_code: string | null; name: string; slug: string; email: string | null; status: string; plan: string | null; subscription_status: string | null }>; links: Array<{ url: string | null; label: string; active: boolean }>; current_page: number; last_page: number };
    filters: { search: string; feature: 'pos' | 'online_store' | null };
    plans: Array<{ id: number; name: string }>;
    metrics: { subscriber_count: number; active_count: number; suspended_count: number; active_subscriptions: number; workspace_users: number };
}>();

const search = ref(props.filters.search);
const enrolling = ref(false);
const accessLabel = props.filters.feature === 'pos' ? 'POS access' : props.filters.feature === 'online_store' ? 'Online Store access' : null;
const enrollment = useForm({ name: '', username: '', email: '', password: '', business_name: '', plan_id: props.plans[0]?.id ?? '' });
const submitSearch = (): void => router.get(route('super-admin.tenants.index'), { search: search.value.trim() || undefined, feature: props.filters.feature ?? undefined }, { preserveState: true, replace: true });
const clearSearch = (): void => { search.value = ''; submitSearch(); };
const enrol = (): void => enrollment.post(route('super-admin.users.store'), { onSuccess: () => { enrollment.reset(); enrolling.value = false; } });
</script>

<template>
    <Head title="Subscribers" />
    <main class="flex min-h-screen bg-neutral-50 text-neutral-900"><SuperAdminSidePanel current="tenants" /><section class="min-w-0 flex-1 px-5 py-8 sm:px-10"><div class="mx-auto max-w-5xl space-y-6">
        <header><p class="text-sm font-semibold text-[#e21b23]">{{ accessLabel ?? 'Subscriber management' }}</p><h1 class="mt-1 text-3xl font-black">{{ accessLabel ?? 'Subscribers' }}</h1><p class="mt-2 max-w-3xl text-neutral-500">{{ accessLabel ? `Subscribers whose active plan includes ${accessLabel}. Select a subscriber to view their main administrator, other admins, and cashiers.` : 'Enrol each business once. Its first login is the main administrator; their team members are shown within that subscriber.' }}</p></header>
        <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><EnCard><Users :size="20" class="text-[#e21b23]" /><p class="mt-3 text-sm text-neutral-500">Subscribers</p><p class="mt-1 text-2xl font-bold">{{ metrics.subscriber_count }}</p></EnCard><EnCard><UserCheck :size="20" class="text-green-600" /><p class="mt-3 text-sm text-neutral-500">Active</p><p class="mt-1 text-2xl font-bold">{{ metrics.active_count }}</p></EnCard><EnCard><UserX :size="20" class="text-amber-600" /><p class="mt-3 text-sm text-neutral-500">Suspended</p><p class="mt-1 text-2xl font-bold">{{ metrics.suspended_count }}</p></EnCard><EnCard><WalletCards :size="20" class="text-blue-600" /><p class="mt-3 text-sm text-neutral-500">Active plans</p><p class="mt-1 text-2xl font-bold">{{ metrics.active_subscriptions }}</p></EnCard><EnCard><Users :size="20" class="text-violet-600" /><p class="mt-3 text-sm text-neutral-500">All team members</p><p class="mt-1 text-2xl font-bold">{{ metrics.workspace_users }}</p></EnCard></div>
        <EnCard v-if="!accessLabel"><button type="button" class="flex w-full items-center justify-between text-left" @click="enrolling = !enrolling"><span><span class="block text-lg font-bold">Enrol a subscriber</span><span class="mt-1 block text-sm text-neutral-500">Create the business workspace and its first main administrator.</span></span><ChevronDown :size="20" class="transition" :class="enrolling ? 'rotate-180' : ''" /></button><form v-if="enrolling" class="mt-6 space-y-4 border-t border-neutral-200 pt-6" @submit.prevent="enrol"><EnInput id="subscriber-business" v-model="enrollment.business_name" label="Business name" required /><EnInput id="subscriber-admin" v-model="enrollment.name" label="Main administrator name" required /><EnInput id="subscriber-username" v-model="enrollment.username" label="Administrator username suffix" placeholder="e.g. ama (becomes ES001-ama)" required /><EnInput id="subscriber-email" v-model="enrollment.email" type="email" label="Administrator email" required /><EnInput id="subscriber-password" v-model="enrollment.password" type="password" label="Administrator login password" required /><label class="block text-sm font-medium text-neutral-700">Subscription plan<select v-model="enrollment.plan_id" class="mt-1.5 min-h-11 w-full rounded-md border border-neutral-300 bg-white px-3 text-sm"><option v-for="plan in plans" :key="plan.id" :value="plan.id">{{ plan.name }}</option></select></label><p v-if="enrollment.errors.username || enrollment.errors.email" class="text-sm text-red-700">{{ enrollment.errors.username || enrollment.errors.email }}</p><button type="submit" class="min-h-11 rounded-md bg-[#e21b23] px-5 text-sm font-bold text-white disabled:opacity-60" :disabled="enrollment.processing">Create subscriber and main administrator</button></form></EnCard>
        <EnCard><form class="flex flex-col gap-3" @submit.prevent="submitSearch"><label class="relative"><span class="sr-only">Search subscribers</span><Search :size="18" class="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-neutral-400" /><input v-model="search" type="search" class="min-h-11 w-full rounded-md border border-neutral-300 py-2 pr-10 pl-10 text-sm" placeholder="Search by business, contact, or store URL" /><button v-if="search" type="button" class="absolute top-1/2 right-2 -translate-y-1/2 rounded p-1 text-neutral-400" aria-label="Clear search" @click="clearSearch"><X :size="17" /></button></label><button type="submit" class="min-h-11 rounded-md bg-[#171717] px-5 text-sm font-semibold text-white">Search subscribers</button></form></EnCard>
        <EnCard><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-bold">Subscriber directory</h2><p class="mt-1 text-sm text-neutral-500">{{ tenants.data.length }} subscriber{{ tenants.data.length === 1 ? '' : 's' }} on this page</p></div></div><div v-if="tenants.data.length" class="mt-5 overflow-x-auto"><table class="w-full min-w-[1180px] text-left text-sm"><thead class="border-b border-neutral-200 text-xs font-semibold tracking-wide text-neutral-500 uppercase"><tr><th class="px-3 py-3">Code</th><th class="px-3 py-3">Subscriber</th><th class="px-3 py-3">Contact</th><th class="px-3 py-3">Plan</th><th class="px-3 py-3">Status</th><th class="px-3 py-3">Tenant URLs</th><th class="px-3 py-3 text-right">Actions</th></tr></thead><tbody><tr v-for="tenant in tenants.data" :key="tenant.id" class="border-b border-neutral-100 last:border-0"><td class="px-3 py-4"><span class="rounded bg-neutral-100 px-2 py-1 font-mono text-xs font-bold">{{ tenant.subscriber_code }}</span></td><td class="px-3 py-4"><p class="font-semibold">{{ tenant.name }}</p><p class="mt-1 font-mono text-xs text-neutral-500">/onlinestore/{{ tenant.slug }}</p></td><td class="px-3 py-4 text-neutral-600">{{ tenant.email || 'No contact email' }}</td><td class="px-3 py-4"><p class="font-medium">{{ tenant.plan || 'Not enrolled' }}</p><p v-if="tenant.subscription_status" class="mt-1 text-xs capitalize text-neutral-500">{{ tenant.subscription_status.replace('_', ' ') }}</p></td><td class="px-3 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold capitalize" :class="tenant.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'">{{ tenant.status }}</span></td><td class="px-3 py-4"><a :href="route('tenant.home', { tenant: tenant.id })" target="_blank" class="block font-mono text-xs text-[#e21b23] hover:underline">Online: {{ route('tenant.home', { tenant: tenant.id }) }}</a><a :href="route('tenant.pos', { tenant: tenant.id })" target="_blank" class="mt-1 block font-mono text-xs text-blue-700 hover:underline">POS: {{ route('tenant.pos', { tenant: tenant.id }) }}</a></td><td class="px-3 py-4"><div class="flex justify-end gap-2"><a :href="route('tenant.home', { tenant: tenant.id })" target="_blank" class="inline-flex min-h-9 items-center gap-1.5 rounded-md border border-neutral-300 px-3 text-xs font-bold hover:border-[#e21b23] hover:text-[#e21b23]"><Store :size="15" /> Store</a><Link :href="route('super-admin.tenants.show', { tenant: tenant.id })" class="inline-flex min-h-9 items-center gap-1.5 rounded-md bg-[#e21b23] px-3 text-xs font-bold text-white hover:bg-[#b9151b]"><Settings :size="15" /> Manage</Link></div></td></tr></tbody></table></div><p v-else class="mt-5 rounded-md bg-neutral-50 p-5 text-sm text-neutral-500">No subscribers match this search.</p></EnCard>
        <div v-if="tenants.last_page > 1" class="flex flex-wrap justify-center gap-2 pt-2"><button v-for="link in tenants.links" :key="link.label" type="button" class="rounded-md border px-3 py-2 text-sm" :class="link.active ? 'border-[#e21b23] bg-[#e21b23] text-white' : 'border-neutral-200 bg-white text-neutral-700'" :disabled="!link.url" @click="link.url && router.visit(link.url)"><span v-html="link.label" /></button></div>
    </div></section></main>
</template>
