<script setup lang="ts">
import AdminSidePanel from '@/Components/AdminSidePanel.vue';
import EnCard from '@/Components/EnCard.vue';
import { Head, router } from '@inertiajs/vue3';
import { ref } from 'vue';
const props = defineProps<{ filters: { from: string; to: string }; metrics: { sales: number; revenue_minor: number; discount_minor: number; items: number }; byPayment: Array<{ payment_method: string; total_minor: number; count: number }>; recentSales: Array<{ id: number; transaction_uuid: string; total_minor: number; discount_minor: number; payment_method: string; completed_at: string }> }>();
const tenant = String(route().params.tenant); const mobilePanelOpen = ref(false); const from = ref(props.filters.from); const to = ref(props.filters.to);
const format = (minor: number): string => new Intl.NumberFormat('en-GH', { style: 'currency', currency: 'GHS' }).format(minor / 100);
const filter = (): void => router.get(route('tenant.reports', { tenant }), { from: from.value, to: to.value }, { preserveState: true });
</script>
<template><Head title="Reports" /><main class="min-h-screen bg-neutral-50"><div class="mx-auto flex min-h-screen max-w-[1600px]"><AdminSidePanel :tenant="tenant" current="reports" :mobile-open="mobilePanelOpen" @close="mobilePanelOpen = false" /><section class="min-w-0 flex-1 px-4 py-6 sm:px-8 sm:py-10"><div class="mx-auto max-w-7xl space-y-8"><header class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-red-700">Business intelligence</p><h1 class="mt-1 text-3xl font-bold">Reports</h1></div><form class="flex flex-wrap gap-2" @submit.prevent="filter"><input v-model="from" type="date" class="rounded-md border px-3 py-2 text-sm" /><input v-model="to" type="date" class="rounded-md border px-3 py-2 text-sm" /><button class="rounded-md bg-red-700 px-4 py-2 text-sm font-semibold text-white">Apply</button></form></header><div class="grid gap-4 md:grid-cols-4"><EnCard><p class="text-sm text-neutral-500">Sales</p><p class="mt-2 text-2xl font-bold">{{ metrics.sales }}</p></EnCard><EnCard><p class="text-sm text-neutral-500">Revenue</p><p class="mt-2 text-2xl font-bold">{{ format(metrics.revenue_minor) }}</p></EnCard><EnCard><p class="text-sm text-neutral-500">Discounts</p><p class="mt-2 text-2xl font-bold">{{ format(metrics.discount_minor) }}</p></EnCard><EnCard><p class="text-sm text-neutral-500">Items sold</p><p class="mt-2 text-2xl font-bold">{{ metrics.items }}</p></EnCard></div><EnCard><h2 class="text-lg font-semibold">Recent sales</h2><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b text-xs uppercase text-neutral-500"><tr><th class="px-3 py-3">Transaction</th><th class="px-3 py-3">Payment</th><th class="px-3 py-3">Discount</th><th class="px-3 py-3">Total</th><th class="px-3 py-3">Completed</th></tr></thead><tbody><tr v-for="sale in recentSales" :key="sale.id" class="border-b last:border-0"><td class="px-3 py-3 font-mono text-xs">{{ sale.transaction_uuid.slice(0, 8) }}</td><td class="px-3 py-3 capitalize">{{ sale.payment_method.replace('_', ' ') }}</td><td class="px-3 py-3">{{ format(sale.discount_minor) }}</td><td class="px-3 py-3 font-semibold">{{ format(sale.total_minor) }}</td><td class="px-3 py-3 text-neutral-500">{{ sale.completed_at }}</td></tr></tbody></table></div></EnCard></div></section></div></main></template>
